### ISSUE TITLE
Cannot select games

### ISSUE THREAD

**Issue by bebjanmnin** [RhythmHeavenDevelopment/RhythmHeavenMania#1]
For some reason, whenever I click on a game in the editor to select it, nothing happens. Hovering over the icons still shows the game name. I just built it and haven't touched any files. Windows 10 20H2.

**Comment by Starpelly** [comment]
Did you update to the latest version?

**Comment by bebjanmnin** [comment]
Yes, I am on the latest version, although it hasn't worked in the previous versions I've downloaded either.

**Comment by Starpelly** [comment]
First, update to the push I just made. That should've fixed some problems with plugins. Second, make sure your Unity version is 2020.3.25f1. As that is the one I am developing with, I have no idea what it's like on other versions.

Some more questions:
Is it only when you build the actual project or is it a unity editor issue only? Are there any warnings or errors that pop up when you select a game?

**Comment by bebjanmnin** [comment]
The new update fixed the issue.
