### ISSUE TITLE
Cannot change start position

### ISSUE THREAD

**Issue by bebjanmnin** [RhythmHeavenDevelopment/RhythmHeavenMania#10]
When right-clicking with the selection tool, I can no longer change the start position. I believe this may have something to do with the tempo change tool, as before using it, I was able to change the position, but this bug persists after reloading the same remix after closing and reopening the game, so I am doubtful.

**Comment by Starpelly** [comment]
I don't understand your question. Video example?

**Comment by bebjanmnin** [comment]
After doing more testing, I noticed it is not entirely broken, rather it only works when right-clicking on the black "ruler" area above the timeline. It has worked when right-clicking on the timeline itself in past versions.

**Comment by Starpelly** [comment]
This changed to allow me to do something else when right clicking on the general timeline.
