### ISSUE TITLE
call multiple events at the same time does not get the type correctly

### ISSUE THREAD

**Issue by shshwdr** [RhythmHeavenDevelopment/RhythmHeavenMania#12]
When I call multiple event at the same time, it seems the `currentEvent `was not updated in `eventCaller.CallEvent(entitesAtSameBeat[i].datamodel);` so 
`currentLength = GameManager.instance.Beatmap.entities[GameManager.instance.currentEvent].length;`
and the following would always use the value of the first event.
I temporarily fix this with adding `currentEvent++;` after `eventCaller.CallEvent(entitesAtSameBeat[i].datamodel);`  and change `currentEvent += entitesAtSameBeat.Count + gameManagerEntities.Count;` to `currentEvent += gameManagerEntities.Count;`
Not sure if this is a correct fix or I missed something.

**Comment by Starpelly** [comment]
Oh wow, this actually makes a lot of sense. Since it doesn't update the current event until the for loop is over it will continue to use the event index that was last present when calling the function. How did I let this slip through?

Thank you for bringing this to my attention.
