### ISSUE TITLE
Fork Lifter Sideways Objects

### ISSUE THREAD

**Issue by Seanski2** [RhythmHeavenDevelopment/RhythmHeavenMania#14]
While trying to simultaneously gulp and skewer a food item, the food item will be stuck on its side.

https://user-images.githubusercontent.com/65259418/152042417-da80559f-3125-4ba3-8529-09ded22154ca.mp4

**Comment by Starpelly** [comment]
Fixed:
https://github.com/RhythmHeavenDevelopment/RhythmHeavenMania/commit/acc68f6eb1b2d92152d1eac78b0b0bedc02beb01
