### ISSUE TITLE
Duplicate files?

### ISSUE THREAD

**Issue by bebjanmnin** [RhythmHeavenDevelopment/RhythmHeavenMania#3]
When I downloaded the newest release, I ran into a bunch of compiler errors when trying to build it. I noticed that there were duplicate files stored in two different folders. This had happened in the past, but deleting/renaming/moving the duplicates did not work this time. I also got a bunch of other compile errors because of duplicate functions (is that what you call them? i'm a lowly web developer i do not know the nomenclature) inside the scripts. What's with all the duplicates? A screenshot of the specific console errors I'm getting is here: https://i.imgur.com/VxufjBz.png . Windows 10 20H2.

**Comment by Starpelly** [comment]
I'm not able to replicate this. My best advice for you is to download and try it again.

**Comment by bebjanmnin** [comment]
Yeah this one was on me. I had been replacing the RHM folder instead of deleting the old version first, which messed with file placements.
