### ISSUE TITLE
Space Soccer Autoplay Desync

### ISSUE THREAD

**Issue by Seanski2** [RhythmHeavenDevelopment/RhythmHeavenMania#5]
https://streamable.com/84upz4
Space Soccer slowly desyncs when on autoplay. I'd test it with my own inputs, but input latency is rearing its ugly head.

**Comment by Starpelly** [comment]
Regarding input latency, I've been trying to find a solution to that for weeks.
Fixed:
https://github.com/RhythmHeavenDevelopment/RhythmHeavenMania/commit/a6fcba54c1b9844454e7052c8fb9ec7af9e5d6ed
