### ISSUE TITLE
Karate Man Combo Miss Bugs

### ISSUE THREAD

**Issue by Seanski2** [RhythmHeavenDevelopment/RhythmHeavenMania#6]
Completely missing the barrel after starting a combo results in a bug where the "shock" face appears on the back of Karate Joe's head; completely missing either part of the combo will misplace the small shock visual effect where it would usually appear in Joe's default stance.
![image](https://user-images.githubusercontent.com/65259418/151244108-c2042b85-ccc1-40e5-a24a-1be9e96d54df.png)

**Comment by Starpelly** [comment]
Oh wow, I would have never caught that.
Fixed:
https://github.com/RhythmHeavenDevelopment/RhythmHeavenMania/commit/21aa06150ec833d5f9b12effc63bf191f22a072f
