### ISSUE TITLE
Clappy Trio Autoplay (Again)

### ISSUE THREAD

**Issue by Seanski2** [RhythmHeavenDevelopment/RhythmHeavenMania#7]
https://streamable.com/fuua69
The Clappy Trio Autoplay stops working after the first clap cue; this behavior "resets" itself upon game switch.

**Comment by Seanski2** [comment]
Update: It seems like it's impossible to hit this second clap while playing, as it always results in a miss, or at least it seems so.

**Comment by Starpelly** [comment]
I forgot literally one line of code
https://github.com/RhythmHeavenDevelopment/RhythmHeavenMania/blob/8f268f4d6073dc61ed2c544f733adf07f81f2183/Assets/Scripts/Games/ClappyTrio/ClappyTrioPlayer.cs#L93
