### ISSUE TITLE
Karate Man Back of Head Retainment

### ISSUE THREAD

**Issue by Seanski2** [RhythmHeavenDevelopment/RhythmHeavenMania#8]
https://streamable.com/voyjje
The video displays this better than I can describe, but Karate Joe's face keeps its "back-of-head" texture after hitting a pot directly after a combo. Persists until game switch.

**Comment by Seanski2** [comment]
https://streamable.com/76lels
After some further testing... _something_ result in Karate Joe's face appearing on the back of his head (as demonstrated in the earlier combo miss issue, albeit with the idle face compared to the miss one) before returning to normal as he changes his stance. It seems random; sometimes it'll happen on one beat, and after playing again it won't. If it doesn't occur, the bug from above will occur instead.

**Comment by Starpelly** [comment]
Fixed:
https://github.com/RhythmHeavenDevelopment/RhythmHeavenMania/commit/df5a64622e0fa5b88e32fc39b6c34715d19beb62
