### ISSUE TITLE
Karate Man switch drops cues

### ISSUE THREAD

**Issue by bebjanmnin** [RhythmHeavenDevelopment/RhythmHeavenMania#9]
When switching games to Karate Man, pot cues are dropped and don't occur. This is very inconvenient for cool transitions. https://streamable.com/i7uryn

**Comment by Starpelly** [comment]
Fixed:
https://github.com/RhythmHeavenDevelopment/RhythmHeavenMania/commit/eee8a3952fc4ea0b79c83402ac33665773a7dd67
